### ISSUE TITLE
Run Command

### ISSUE THREAD

**Issue by daudirsch** [MarcoDuff/vscode-appcelerator#1]
Is it possible to use the Run command on a specified simulator?  For example, I'm using genymotion for an Android emulator.

**Comment by MarcoDuff** [comment]
@daudirsch At the moment no, but give me the command line that you use to run genymotion and i will add it to next release.

**Comment by daudirsch** [comment]
First, thanks for the response and the tool.  You call it from the CLI like:

appc run -p android -C <GENYMOTION_AVD_NAME>
## Example
appc run -p android -C "Nexus 7 - 4.2.2 - API 17 - 800x1280"

To get a complete list of Android virtual devices, run the ti info -t
android command. The Genymotion devices are listed at the end right before
any warning messages.

Here's the appcelerator document on it.

http://docs.appcelerator.com/platform/latest/#!/guide/Installing_Genymotion-section-src-37550296_InstallingGenymotion-LaunchaGenymotionVirtualDevicefromtheCLI

**Comment by MarcoDuff** [comment]
May you please share with me your `appc info -o json`: i need to know where you have the string  "Nexus 7 - 4.2.2 - API 17 - 800x1280"

**Comment by MarcoDuff** [comment]
I have checked my output and i have this two fields:

>     "emulators": [
>       {
>         "type": "avd",
>         "id": "Android_ARMv7a",
>         "name": "Android_ARMv7a",
>         "device": "undefined (undefined)",
>         "path": "/Users/MarcoDuff/.android/avd/Android_ARMv7a.avd",
>         "target": "Android 6.0 (API level 23)",
>         "abi": "armeabi-v7a",
>         "skin": "768x1280",
>         "sdcard": "/Users/MarcoDuff/.android/avd/Android_ARMv7a.avd/sdcard.img",
>         "googleApis": true,
>         "sdk-version": "6.0",
>         "api-level": 23
>       },
>       {
>         "type": "avd",
>         "id": "Android_Accelerated_x86",
>         "name": "Android_Accelerated_x86",
>         "device": "undefined (undefined)",
>         "path": "/Users/MarcoDuff/.android/avd/Android_Accelerated_x86.avd",
>         "target": "Android 6.0 (API level 23)",
>         "abi": "x86",
>         "skin": "768x1280",
>         "sdcard": "/Users/MarcoDuff/.android/avd/Android_Accelerated_x86.avd/sdcard.img",
>         "googleApis": true,
>         "sdk-version": "6.0",
>         "api-level": 23
>       }
>     ]

and 

  

> "genymotion": {
>     "executables": {
>       "genymotion": null,
>       "player": null,
>       "vboxmanage": null
>     },
>     "home": null,
>     "avds": [
>       
>     ],
>     "issues": [
>       
>     ],
>     "tisdk": "6.3.0.v20171018084007"
>   },

I think that you have some avds under `genymotion` fields. May you confirm that?

**Comment by daudirsch** [comment]
Yes, I do.  "Samsung Galaxy S8 - 7.0.0 - API 24 - 1440x2960"

The full output:
Genymotion Emulators
  Samsung Galaxy S8 - 7.0.0 - API 24 - 1440x2960
    ID                        = Samsung Galaxy S8 - 7.0.0 - API 24 -
1440x2960
    SDK Version               = 7.0 (android-24)
    ABI                       = x86
    Genymotion Version        = 2.9.0
    Display                   = 1440x2960-16
    DPI                       = 640
    OpenGL Acceleration       = yes
    Google APIs               = no

**Comment by MarcoDuff** [comment]
Perfect, may you please copy and paste your entire "genymotion" field when you run `appc info -o json`, ty.

**Comment by daudirsch** [comment]
Here you go.

"genymotion": {
        "path": "/Applications/Genymotion.app/Contents/MacOS",
        "executables": {
            "genymotion":
"/Applications/Genymotion.app/Contents/MacOS/genymotion",
            "player":
"/Applications/Genymotion.app/Contents/MacOS/player.app/Contents/MacOS/player",
            "vboxmanage": "/usr/local/bin/VBoxManage"
        },
        "home": "/Users/daudirsch/.Genymobile/Genymotion",
        "avds": [
            {
                "name": "Samsung Galaxy S8 - 7.0.0 - API 24 - 1440x2960",
                "guid": "21cf7558-aae5-4d4c-88ec-686aea432ba9",
                "type": "genymotion",
                "abi": "x86",
                "googleApis": false,
                "sdk-version": "7.0",
                "hardwareOpenGL": true,
                "display": "1440x2960-16",
                "dpi": 640,
                "genymotion": "2.9.0",
                "target": "7.0",
                "ipaddress": "192.168.56.101",
                "api-level": 24,
                "id": "Samsung Galaxy S8 - 7.0.0 - API 24 - 1440x2960"
            }
        ],
        "issues": [],
        "virtualbox": "5.1.28r117968",
        "tisdk": "6.2.2.GA"
    },

**Comment by MarcoDuff** [comment]
Done, please download version 1.0.5.

Ty @daudirsch
